version: '3.8'

services:
  # React WordPress API Frontend
  react-wordpress:
    build: .
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - wordpress-network

  # Optional: WordPress with MySQL (for development/testing)
  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - wordpress-network

  # MySQL Database for WordPress
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress_password
      MYSQL_ROOT_PASSWORD: root_password
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - wordpress-network

  # phpMyAdmin (optional - for database management)
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root_password
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - wordpress-network

  # Laravel Backend API
  laravel-backend:
    build: ./laravel-backend
    ports:
      - "8000:9000"
    environment:
      - APP_ENV=production
      - APP_KEY=base64:your-generated-key-here
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel_wordpress
      - DB_USERNAME=laravel
      - DB_PASSWORD=laravel_password
      - CACHE_DRIVER=redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - WORDPRESS_API_URL=https://public-api.wordpress.com/rest/v1.1/sites/jcreforme.home.blog
      - WORDPRESS_SITE_URL=https://jcreforme.home.blog
    volumes:
      - ./laravel-backend:/var/www/laravel
    depends_on:
      - mysql
      - redis
    restart: unless-stopped
    networks:
      - wordpress-network

  # Redis for Laravel caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - wordpress-network

  # Nginx for Laravel
  nginx:
    image: nginx:alpine
    ports:
      - "8001:80"
    volumes:
      - ./laravel-backend:/var/www/laravel
      - ./nginx-laravel.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel-backend
    restart: unless-stopped
    networks:
      - wordpress-network

volumes:
  wordpress_data:
  mysql_data:
  redis_data:
  redis_data:

networks:
  wordpress-network:
    driver: bridge
